# theme.toml template for a Hugo theme
# See https://github.com/gohugoiox/hugoThemes#themetoml for an example

name = "Arriva Api"
license = "MIT"
licenselink = "https://www.arriva.cz/"
description = "Arriva API documentation"
homepage = "https://www.arriva.cz/"
demosite = "https://www.arriva.cz/"
tags = ["Documentation"]
min_version = "0.0.1"

[author]
  name = "Arriva"
  homepage = "https://www.arriva.cz/"
